feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      jsonplaceholder:
        connectTimeout: 5000
        readTimeout: 5000





app:
  feign:
    client:
      name: jsonplaceholder
      url:  https://jsonplaceholder.typicode.com/

logging:
  level:
    com.tryout.spring: DEBUG